"""empty message

Revision ID: 93492173000b
Revises: 9d29a554565e
Create Date: 2023-11-10 12:25:37.632401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93492173000b'
down_revision = '9d29a554565e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('late',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coursename', sa.String(length=100), nullable=False),
    sa.Column('studentname', sa.String(length=100), nullable=False),
    sa.Column('lateday', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('late')
    # ### end Alembic commands ###
